version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
